name       : sane-airscan
version    : 0.99.27
release    : 1
source     : 
    - https://github.com/alexpevzner/sane-airscan/archive/refs/tags/0.99.27.tar.gz : 0d84ca10f9e80d8f5f6bc0f30911660667b6d5b9df8d3fd45be0dcc29775aa84
license    : GPL-2.0-or-later
component  : office
summary    : SANE backend for AirScan (eSCL) and WSD document scanners
description: |
    SANE backend for MFP and document scanners that implements either eSCL (AirScan/AirPrint scanning) or WSD "driverless" scanning protocol.
builddeps  :
  - pkgconfig(libinsane)
  - pkgconfig(libxml-2.0)
  - pkgconfig(avahi-client)
  - pkgconfig(libjpeg)
  - pkgconfig(libpng)
  - pkgconfig(gnutls)
build      : |
    %make
install    : |
    %make_install
